version: "3"

services:
        app:
                build: .
                command: npm run dev
                volumes:
                        - .:/app/
                        - /app/node_modules
                        - /app/db
                ports:
                        - "8081:8081"
